### ISSUE TITLE
Python 2/3 compatability

### ISSUE THREAD

**Issue by moshekaplan** [moshekaplan/python-sha3#2]
Add Python 3 support.

**Comment by fionafibration** [comment]
Seconded

**Comment by moshekaplan** [comment]
Per  https://docs.python.org/3/library/hashlib.html 👍 

> New in version 3.6: SHA3 (Keccak) and SHAKE constructors sha3_224(), sha3_256(), sha3_384(), sha3_512(), shake_128(), shake_256(). 

Seems like Py3 compatability isn't needed, since it's now a built-in.
